Budget/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Threax.AspNetCore.UserBuilder.Entities;

namespace Budget.Controllers
{
    [Authorize(AuthenticationSchemes = AuthCoreSchemes.Cookies)]
    public class AdminController : Controller
    {
        [Authorize(Roles = AuthorizationAdminRoles.EditRoles)]
        public IActionResult Users()
        {
            return View();
        }
    }
}

Budget/Views/Shared/Footer.cshtml
<div class="container">
    <hr />
</div>
<relogin></relogin>

Budget/Views/Shared/Header.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-brand-app" data-hr-controller="appMenu">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Budget</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Categories">Categories</a></li>

                <li class="nav-item dropdown startHidden" data-hr-toggle="admin" data-hr-class-on="d-block">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="adminMenu">Admin <span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="adminMenu">
                        <a class="dropdown-item startHidden" data-hr-class-on="d-block" data-hr-toggle="users" asp-area="" asp-controller="Admin" asp-action="Users">Users</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav startHidden" data-hr-toggle="loggedInArea" data-hr-class-on="d-block">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="userMenu" data-hr-view="userInfo">{{userName}} <span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="userMenu">
                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

Budget/Views/Shared/_CachePage.cshtml
@inject Threax.AspNetCore.Mvc.CacheUi.ICacheUiRenderData renderData;
@{
    renderData.Title = ViewData["Title"]?.ToString();
}
@RenderBody()
<page-runner></page-runner>

Budget/Views/Shared/_CacheRoot.cshtml
@inject Threax.AspNetCore.Mvc.CacheUi.ICacheUiRenderData renderData;
@{
    Layout = "_Layout";
}
<script type="text/javascript" src="@renderData.ContentLink"></script>

Budget/Views/Shared/_Layout.cshtml
@{
    Layout = "_LayoutTop";
}
<script type="text/javascript" src="@Url.CacheUiActionLink(nameof(HomeController.Header), typeof(HomeController))"></script>
<div class="container body-content mt-3">@RenderBody()</div>
<script type="text/javascript" src="@Url.CacheUiActionLink(nameof(HomeController.Footer), typeof(HomeController))"></script>

Budget/Views/Shared/_LayoutTop.cshtml
@using Threax.AspNetCore.AuthCore;
@inject Threax.AspNetCore.Halcyon.Ext.IEntryPointRenderer entryPointRenderer;
<!DOCTYPE html><html><head><style csp-nonce>html{visibility:hidden;opacity:0;background-color: #222;}</style><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/favicon.ico?v=1")" /><title>@ViewData["Title"] - Budget</title>
<asset-bundle src="~/bundle.min.css"></asset-bundle>@RenderSection("css", required: false)<link rel="manifest" href="@Url.Content("~/webmanifest.json")"></head><body>
@RenderBody()
<client-config csp-nonce></client-config>
<script type="text/javascript" csp-nonce>window.hr_config=(function(next){return function(config){config.entry = @Html.Raw(entryPointRenderer.Render().ToString(Newtonsoft.Json.Formatting.None));return next?next(config):config;}})(window.hr_config);</script>
<style csp-nonce>html{visibility:visible;opacity:1;}</style>
<asset-bundle src="~/bundle.min.js"></asset-bundle>@RenderSection("scripts", required: false)<script type="text/javascript" src="~/lib/jsns/runattributes.js" asp-append-version="true"></script>
<threax-csp></threax-csp>
</body></html>